# -*- coding: utf-8 -*-
"""
Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xmaq1dT1lTkcyOuiCJrOS2OMbYZoU4Qo
"""

import time
from collections import deque

class ParkingLot:
    """
    Parking Management System (DSA-oriented)
    ------------------------------------------------------------
      - Zone: C1..C10 (car), M1..M10 (motorbike), B1..B10 (other)
      - Core data structures:
          * Hash Table (dict): index / parking_lot: plate -> record
          * Queue (deque): waiting_queue (FIFO)
          * Array/List pool: free_slots_pool[zone] (slot ids available)
          * Occupied set: zone_occupied[zone] (slot ids in-use) -> O(1) add/remove
          * Counters: zone_count[zone], current_total
      - Invariants:
          (1) zone_count[z] == len(zone_occupied[z])
          (2) len(free_slots_pool[z]) + len(zone_occupied[z]) == max_capacity_zone[z]
          (3) current_total == sum(zone_count[z] for z in all zones)
    """

    # -----------------------------
    # NODE 0: INIT / SETUP SYSTEM
    # -----------------------------
    def __init__(self):
        # Queue: xe chờ (WAITING) - FIFO
        self.waiting_queue = deque()

        # Hash Table: plate -> record
        # (đúng theo design: index)
        self.index = {}

        # Define zones
        self.zones = (
            [f"C{i}" for i in range(1, 11)] +  # cars
            [f"M{i}" for i in range(1, 11)] +  # motorbikes
            [f"B{i}" for i in range(1, 11)]    # other
        )

        # Capacity per zone (100 slots each)
        self.max_capacity_zone = {z: 100 for z in self.zones}

        # Occupied slots per zone (set -> O(1) add/remove)
        self.zone_occupied = {z: set() for z in self.zones}

        # Free slots pool per zone (list of slot ids 0..99)
        self.free_slots_pool = {z: list(range(self.max_capacity_zone[z])) for z in self.zones}

        # Counters
        self.zone_count = {z: 0 for z in self.zones}
        self.current_total = 0

    # ------------------------------------------
    # NODE 1: CHECK-IN ENTRY POINT (vehicle in)
    # ------------------------------------------
    def vehicle_entry(self, vehicle_type: str, plate: str):
        """
        CHECK-IN flow:
          1) Validate input
          2) Duplicate check in Hash Table (index)
          3) If full -> enqueue WAITING
          4) Else -> recommend zones (top K)
          5) Guard selects zone (human-in-loop)
          6) Allocate slot from free_slots_pool[zone]
          7) Update index + counters + occupied sets (maintain invariants)
        """
        vehicle_type = vehicle_type.strip().lower()
        plate = plate.strip().upper()

        if not plate:
            print("Biển số không hợp lệ.")
            return

        # (Step 2) Duplicate check: nếu xe đang IN thì reject
        if plate in self.index and self.index[plate]["status"] == "IN":
            print(f"Xe {plate} đã có trong bãi (IN).")
            return

        expected_prefix = self._prefix_for_type(vehicle_type)
        if expected_prefix is None:
            print("Loại xe không hợp lệ. Chỉ nhận: car / motorbike / other.")
            return

        # (Step 3) Nếu toàn bộ zone của loại đó đều full -> WAITING
        if not self._has_available_zone(expected_prefix):
            print("Toàn bộ bãi cho loại xe này đã đầy. Xe sẽ vào hàng đợi WAITING.")
            self._enqueue_waiting(vehicle_type, plate)
            return

        # (Step 4) Recommend zones
        recommended = self.suggest_zone(vehicle_type)
        print("\n--- CHECK-IN ---")
        print(f"Các zone gợi ý: {', '.join(recommended)}")
        zone = input("Chọn zone (vd: C1, M3, B2): ").strip().upper()

        if zone not in self.max_capacity_zone:
            print("Zone không tồn tại. Xe sẽ vào hàng đợi WAITING.")
            self._enqueue_waiting(vehicle_type, plate)
            return

        if not zone.startswith(expected_prefix):
            print("Chọn sai loại zone. Xe sẽ vào hàng đợi WAITING.")
            self._enqueue_waiting(vehicle_type, plate)
            return

        # (Step 6,7) Allocate & update
        self._assign_parking_slot(vehicle_type, plate, zone)

    # -------------------------------------------------
    # NODE 2: CHECK-OUT ENTRY POINT (vehicle out)
    # -------------------------------------------------
    def vehicle_exit(self, plate: str):

        plate = plate.strip().upper()

        if plate not in self.index:
            print("Xe không có trong hệ thống (NOT FOUND).")
            return

        record = self.index[plate]
        status = record["status"]

        print("\n--- CHECK-OUT ---")

        if status == "WAITING":
            removed = self.remove_vehicle_from_waiting_queue(plate, silent=True)
            if removed:
                del self.index[plate]
                print(f"Xe {plate} đang WAITING -> đã hủy chờ và xóa khỏi hệ thống.")
            else:
                del self.index[plate]
                print(f"Xe {plate} WAITING -> xóa khỏi index (không tìm thấy trong queue).")
            return
        if status == "OUT":
            print(f"Xe {plate} đã OUT trước đó.")
            return
        if status != "IN":
            print("Trạng thái xe không hợp lệ.")
            return

        entry_time = record["time_in"]
        exit_time = time.time()
        parked_time = exit_time - entry_time

        fee = self.calculate_fee(parked_time, record["vehicle_type"])
        total_minutes = int(parked_time // 60)
        hours = total_minutes // 60
        minutes = total_minutes % 60
        duration_str = f"{hours} giờ {minutes} phút"

        print(f"Xe {plate} ra khỏi bãi. Thời gian đỗ: {duration_str}. Phí: {fee} VND.")
        print(f"Thời gian vào: {time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(entry_time))}")
        print(f"Thời gian ra : {time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(exit_time))}")

        zone = record["zone"]
        slot = record["slot"]
        self.zone_occupied[zone].remove(slot)         # O(1)
        self.free_slots_pool[zone].append(slot)       # O(1)
        self.zone_count[zone] -= 1
        self.current_total -= 1
        record["time_out"] = exit_time
        record["status"] = "OUT"

        self._admit_waiting_fifo()

        # optional invariant check
        if not self._check_invariants():
            print("⚠️ Cảnh báo: invariant bị vi phạm (kiểm tra lại logic cập nhật dữ liệu).")

    # -------------------------------------------------
    # NODE 3: ZONE RECOMMENDATION (top K by remaining)
    # -------------------------------------------------
    def suggest_zone(self, vehicle_type: str, top_k: int = 3):
        """
        Recommend zones by remaining capacity descending.
        remaining(z) = max_capacity_zone[z] - zone_count[z]
        """
        vehicle_type = vehicle_type.strip().lower()
        prefix = self._prefix_for_type(vehicle_type)
        if prefix is None:
            return []

        candidates = [z for z in self.zones if z.startswith(prefix)]
        remaining = [(z, self.max_capacity_zone[z] - self.zone_count[z]) for z in candidates]
        remaining = [x for x in remaining if x[1] > 0]

        remaining.sort(key=lambda x: (-x[1], x[0]))  # stable tie-break
        return [z for z, _ in remaining[:top_k]]

    # -----------------------------------------
    # NODE 4: FEE SERVICE (billing)
    # -----------------------------------------
    def calculate_fee(self, parked_time: float, vehicle_type: str) -> int:
        """
        Tính phí theo giờ (đơn giản).
        Bạn có thể thay đổi rule theo yêu cầu.
        """
        vehicle_type = vehicle_type.strip().lower()
        hours_parked = int(parked_time // 3600)

        # Fee tables
        fees = {
            "car":        (20000, 40000, 60000, 120000),
            "motorbike":  (10000, 20000, 30000, 60000),
            "other":      (5000,  10000, 15000, 30000),
        }
        if vehicle_type not in fees:
            return 0

        fee_1, fee_2, fee_3, fee_extra = fees[vehicle_type]

        if hours_parked <= 3:
            return fee_1
        elif hours_parked <= 13:
            return fee_2
        elif hours_parked < 24:
            return fee_3
        else:
            return fee_extra

    # -----------------------------------------
    # NODE 5: SEARCH (plate lookup - O(1))
    # -----------------------------------------
    def find_vehicle(self, plate: str):
        plate = plate.strip().upper()
        if plate not in self.index:
            print(f"Xe {plate} không có trong hệ thống.")
            return

        rec = self.index[plate]
        print(f"Xe {plate} - trạng thái: {rec['status']}")
        if rec["status"] == "IN":
            print(f"Đang ở: {rec['spot']}")
            print(f"Thời gian vào: {time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(rec['time_in']))}")
        elif rec["status"] == "WAITING":
            print("Xe đang ở hàng đợi WAITING.")
        else:
            print("Xe đã OUT.")
            print(f"Thời gian vào: {time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(rec['time_in']))}")
            print(f"Thời gian ra : {time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(rec['time_out']))}")

    # -----------------------------------------
    # NODE 6: WAITING QUEUE ops
    # -----------------------------------------
    def _enqueue_waiting(self, vehicle_type: str, plate: str):
        # tránh duplicate waiting
        if plate in self.index and self.index[plate]["status"] == "WAITING":
            print(f"Xe {plate} đã ở WAITING.")
            return

        now = time.time()
        self.waiting_queue.append((vehicle_type, plate))
        self.index[plate] = {
            "vehicle_type": vehicle_type,
            "zone": None,
            "slot": None,
            "time_in": now,
            "time_out": None,
            "status": "WAITING",
            "spot": "WAITING_QUEUE",
        }
        print(f"Xe {plate} -> WAITING (đã đưa vào hàng đợi).")

    def remove_vehicle_from_waiting_queue(self, plate: str, silent: bool = False) -> bool:
        """
        Xóa xe khỏi hàng đợi nếu khách không muốn chờ nữa.
        Trả về True nếu xóa được, False nếu không có.
        """
        plate = plate.strip().upper()
        before = len(self.waiting_queue)
        self.waiting_queue = deque([(t, p) for (t, p) in self.waiting_queue if p != plate])
        after = len(self.waiting_queue)
        removed = after < before

        if not silent:
            if removed:
                print(f"Xe {plate} đã được xóa khỏi hàng đợi.")
            else:
                print(f"Xe {plate} không có trong hàng đợi.")
        return removed

    def show_waiting_queue(self):
        print("\n--- Hàng đợi xe (WAITING) ---")
        if not self.waiting_queue:
            print("Hàng đợi trống.")
        else:
            for i, (v_type, plate) in enumerate(self.waiting_queue, 1):
                print(f"{i}. Loại xe: {v_type}, Biển số: {plate}")
        print("-----------------------------")

    # -----------------------------------------
    # NODE 7: STATUS DISPLAY
    # -----------------------------------------
    def show_parking_status(self):
        """
        Hiển thị tình trạng theo từng zone (used/total).
        """
        print("\n--- Tình trạng bãi đỗ ---")

        def print_group(prefix, title):
            print(f"\n{title}:")
            for i in range(1, 11):
                z = f"{prefix}{i}"
                used = self.zone_count[z]
                cap = self.max_capacity_zone[z]
                print(f"  Zone {z}: {used} / {cap} đã sử dụng (còn {cap - used}).")

        print_group("C", "Tầng 1 (Ô tô)")
        print_group("M", "Tầng 2 (Xe máy)")
        print_group("B", "Tầng 3 (Xe linh tinh)")

        print(f"\nTổng xe đang IN trong bãi: {self.current_total}")

    # ============================================================
    # INTERNAL HELPERS (keep system clean, avoid mixing logic)
    # ============================================================

    def _prefix_for_type(self, vehicle_type: str):
        mapping = {"car": "C", "motorbike": "M", "other": "B"}
        return mapping.get(vehicle_type.strip().lower())

    def _has_available_zone(self, prefix: str) -> bool:
        for i in range(1, 11):
            z = f"{prefix}{i}"
            if self.zone_count[z] < self.max_capacity_zone[z]:
                return True
        return False

    def _assign_parking_slot(self, vehicle_type: str, plate: str, zone: str):
        # capacity check
        if self.zone_count[zone] >= self.max_capacity_zone[zone]:
            print(f"Zone {zone} đã đầy. Xe sẽ vào WAITING.")
            self._enqueue_waiting(vehicle_type, plate)
            return

        if not self.free_slots_pool[zone]:
            print(f"Hết slot trong {zone}. Xe sẽ vào WAITING.")
            self._enqueue_waiting(vehicle_type, plate)
            return

        slot = self.free_slots_pool[zone].pop()
        self.zone_occupied[zone].add(slot)

        now = time.time()
        self.index[plate] = {
            "vehicle_type": vehicle_type,
            "zone": zone,
            "slot": slot,
            "time_in": now,
            "time_out": None,
            "status": "IN",
            "spot": f"{zone} - Ô {slot + 1}",
        }

        self.zone_count[zone] += 1
        self.current_total += 1

        print(f"✅ Xe {plate} vào {zone} - Ô {slot + 1}.")

        # optional invariant check
        if not self._check_invariants():
            print("⚠️ Cảnh báo: invariant bị vi phạm sau CHECK-IN.")

    def _admit_waiting_fifo(self):
        """
        Admit WAITING vehicles in FIFO order when slots become available.
        Rule: pick the best recommended zone (top 1) and auto-assign.
        (đúng design: WAITING -> IN khi có slot)
        """
        while self.waiting_queue:
            v_type, plate = self.waiting_queue[0]
            prefix = self._prefix_for_type(v_type)
            if prefix is None:
                # loại xe sai - loại khỏi queue
                self.waiting_queue.popleft()
                if plate in self.index:
                    self.index[plate]["status"] = "OUT"
                continue

            rec = self.suggest_zone(v_type, top_k=1)
            if not rec:
                # chưa có slot cho loại xe này -> dừng
                break

            # có slot -> nhận xe chờ
            self.waiting_queue.popleft()
            self._assign_parking_slot(v_type, plate, rec[0])
            print(f"➡️ Xe WAITING {plate} đã được nhận vào bãi (auto-assign {rec[0]}).")

    def _check_invariants(self) -> bool:
        # (1) zone_count[z] == len(occupied[z])
        for z in self.zones:
            if self.zone_count[z] != len(self.zone_occupied[z]):
                return False

        # (2) free + occupied == capacity
        for z in self.zones:
            if len(self.free_slots_pool[z]) + len(self.zone_occupied[z]) != self.max_capacity_zone[z]:
                return False

        # (3) current_total == sum zone_count
        if self.current_total != sum(self.zone_count[z] for z in self.zones):
            return False

        # (4) record IN must have zone/slot
        for plate, rec in self.index.items():
            if rec["status"] == "IN":
                if rec["zone"] is None or rec["slot"] is None:
                    return False
            if rec["status"] == "WAITING":
                # WAITING must exist in queue (soft check)
                # (không bắt buộc O(n) scan, nhưng ta check nhẹ khi cần)
                pass

        return True

    # -----------------------------------------
    # NODE 8: TERMINAL UI (demo)
    # -----------------------------------------
    def terminal(self):
        while True:
            print("\n========== PARKING MANAGEMENT ==========")
            print("1. Check-in (Xe vào bãi)")
            print("2. Check-out (Xe ra bãi)")
            print("3. Tìm xe theo biển số")
            print("4. Hiển thị tình trạng bãi")
            print("5. Hiển thị hàng đợi WAITING")
            print("6. Hủy WAITING (xóa xe khỏi hàng đợi)")
            print("7. Thoát")
            choice = input("Chọn chức năng: ").strip()

            if choice == "1":
                vehicle_type = input("Loại xe (car/motorbike/other): ")
                plate = input("Biển số xe: ")
                self.vehicle_entry(vehicle_type, plate)

            elif choice == "2":
                plate = input("Biển số xe: ")
                self.vehicle_exit(plate)

            elif choice == "3":
                plate = input("Biển số xe: ")
                self.find_vehicle(plate)

            elif choice == "4":
                self.show_parking_status()

            elif choice == "5":
                self.show_waiting_queue()

            elif choice == "6":
                plate = input("Biển số xe cần hủy WAITING: ")
                removed = self.remove_vehicle_from_waiting_queue(plate)
                if removed and plate in self.index and self.index[plate]["status"] == "WAITING":
                    del self.index[plate]  # đồng bộ index
                    print(f"Đã xóa {plate} khỏi index (WAITING).")

            elif choice == "7":
                print("Thoát chương trình.")
                break
            else:
                print("Lựa chọn không hợp lệ.")


if __name__ == "__main__":
    parking_lot = ParkingLot()
    parking_lot.terminal()



import time
from collections import deque

class ParkingLot:
    """
    Parking Management System (DSA-oriented)
    ------------------------------------------------------------
      - Zone: C1..C10 (car), M1..M10 (motorbike), B1..B10 (other)
      - Core data structures:
          * Hash Table (dict): index / parking_lot: plate -> record
          * Queue (deque): waiting_queue (FIFO)
          * Array/List pool: free_slots_pool[zone] (slot ids available)
          * Occupied set: zone_occupied[zone] (slot ids in-use) -> O(1) add/remove
          * Counters: zone_count[zone], current_total
      - Invariants:
          (1) zone_count[z] == len(zone_occupied[z])
          (2) len(free_slots_pool[z]) + len(zone_occupied[z]) == max_capacity_zone[z]
          (3) current_total == sum(zone_count[z] for z in all zones)
    """

    # -----------------------------
    # NODE 0: INIT / SETUP SYSTEM
    # -----------------------------
    def __init__(self):
        # Queue: xe chờ (WAITING) - FIFO
        self.waiting_queue = deque()

        # Hash Table: plate -> record
        # (đúng theo design: index)
        self.index = {}

        # Define zones
        self.zones = (
            [f"C{i}" for i in range(1, 11)] +  # cars
            [f"M{i}" for i in range(1, 11)] +  # motorbikes
            [f"B{i}" for i in range(1, 11)]    # other
        )

        # Capacity per zone (100 slots each)
        self.max_capacity_zone = {z: 100 for z in self.zones}

        # Occupied slots per zone (set -> O(1) add/remove)
        self.zone_occupied = {z: set() for z in self.zones}

        # Free slots pool per zone (list of slot ids 0..99)


        # Counters
        self.zone_count = {z: 0 for z in self.zones}
        self.current_total = 0

    # ------------------------------------------
    # NODE 1: CHECK-IN ENTRY POINT (vehicle in)
    # ------------------------------------------
    def vehicle_entry(self, vehicle_type: str, plate: str):
        """
        CHECK-IN flow:
          1) Validate input
          2) Duplicate check in Hash Table (index)
          3) If full -> enqueue WAITING
          4) Else -> recommend zones (top K)
          5) Guard selects zone (human-in-loop)
          6) Allocate slot from free_slots_pool[zone]
          7) Update index + counters + occupied sets (maintain invariants)
        """
        vehicle_type = vehicle_type.strip().lower()
        plate = plate.strip().upper()

        if not plate:
            print("Biển số không hợp lệ.")
            return

        # (Step 2) Duplicate check: nếu xe đang IN thì reject
        if plate in self.index and self.index[plate]["status"] == "IN":
            print(f"Xe {plate} đã có trong bãi (IN).")
            return

        expected_prefix = self._prefix_for_type(vehicle_type)
        if expected_prefix is None:
            print("Loại xe không hợp lệ. Chỉ nhận: car / motorbike / other.")
            return

        # (Step 3) Nếu toàn bộ zone của loại đó đều full -> WAITING
        if not self._has_available_zone(expected_prefix):
            print("Toàn bộ bãi cho loại xe này đã đầy. Xe sẽ vào hàng đợi WAITING.")
            self._enqueue_waiting(vehicle_type, plate)
            return

        # (Step 4) Recommend zones
        recommended = self.suggest_zone(vehicle_type)
        print("\n--- CHECK-IN ---")
        print(f"Các zone gợi ý: {', '.join(recommended)}")
        zone = input("Chọn zone (vd: C1, M3, B2): ").strip().upper()

        if zone not in self.max_capacity_zone:
            print("Zone không tồn tại. Xe sẽ vào hàng đợi WAITING.")
            self._enqueue_waiting(vehicle_type, plate)
            return

        if not zone.startswith(expected_prefix):
            print("Chọn sai loại zone. Xe sẽ vào hàng đợi WAITING.")
            self._enqueue_waiting(vehicle_type, plate)
            return

        # (Step 6,7) Allocate & update
        self._assign_parking_slot(vehicle_type, plate, zone)

    # -------------------------------------------------
    # NODE 2: CHECK-OUT ENTRY POINT (vehicle out)
    # -------------------------------------------------
    def vehicle_exit(self, plate: str):
        """
        CHECK-OUT flow:
          1) Lookup record in Hash Table
          2) If NOT FOUND -> reject
          3) If WAITING -> cancel waiting (remove queue + delete index)
          4) If IN -> release slot, compute fee, update counters/index
          5) After release, try admit WAITING (FIFO) if capacity available
        """
        plate = plate.strip().upper()

        if plate not in self.index:
            print("Xe không có trong hệ thống (NOT FOUND).")
            return

        record = self.index[plate]
        status = record["status"]

        print("\n--- CHECK-OUT ---")

        # (Step 3) Cancel WAITING
        if status == "WAITING":
            removed = self.remove_vehicle_from_waiting_queue(plate, silent=True)
            if removed:
                del self.index[plate]
                print(f"Xe {plate} đang WAITING -> đã hủy chờ và xóa khỏi hệ thống.")
            else:
                # trường hợp hiếm: index có nhưng queue không có
                del self.index[plate]
                print(f"Xe {plate} WAITING -> xóa khỏi index (không tìm thấy trong queue).")
            return

        # If OUT already
        if status == "OUT":
            print(f"Xe {plate} đã OUT trước đó.")
            return

        # (Step 4) Release slot for IN
        if status != "IN":
            print("Trạng thái xe không hợp lệ.")
            return

        entry_time = record["time_in"]
        exit_time = time.time()
        parked_time = exit_time - entry_time

        fee = self.calculate_fee(parked_time, record["vehicle_type"])

        # print time info
        total_minutes = int(parked_time // 60)
        hours = total_minutes // 60
        minutes = total_minutes % 60
        duration_str = f"{hours} giờ {minutes} phút"

        print(f"Xe {plate} ra khỏi bãi. Thời gian đỗ: {duration_str}. Phí: {fee} VND.")
        print(f"Thời gian vào: {time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(entry_time))}")
        print(f"Thời gian ra : {time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(exit_time))}")

        zone = record["zone"]
        slot = record["slot"]

        # release in data structures
        self.zone_occupied[zone].remove(slot)         # O(1)
        self.free_slots_pool[zone].append(slot)       # O(1)
        self.zone_count[zone] -= 1
        self.current_total -= 1

        # update index status
        record["time_out"] = exit_time
        record["status"] = "OUT"

        # (Step 5) Admit waiting vehicles (FIFO) if possible
        self._admit_waiting_fifo()

        # optional invariant check
        if not self._check_invariants():
            print("⚠️ Cảnh báo: invariant bị vi phạm (kiểm tra lại logic cập nhật dữ liệu).")

    # -------------------------------------------------
    # NODE 3: ZONE RECOMMENDATION (top K by remaining)
    # -------------------------------------------------
    def suggest_zone(self, vehicle_type: str, top_k: int = 3):
        """
        Recommend zones by remaining capacity descending.
        remaining(z) = max_capacity_zone[z] - zone_count[z]
        """
        vehicle_type = vehicle_type.strip().lower()
        prefix = self._prefix_for_type(vehicle_type)
        if prefix is None:
            return []

        candidates = [z for z in self.zones if z.startswith(prefix)]
        remaining = [(z, self.max_capacity_zone[z] - self.zone_count[z]) for z in candidates]
        remaining = [x for x in remaining if x[1] > 0]

        remaining.sort(key=lambda x: (-x[1], x[0]))  # stable tie-break
        return [z for z, _ in remaining[:top_k]]

    # -----------------------------------------
    # NODE 4: FEE SERVICE (billing)
    # -----------------------------------------
    def calculate_fee(self, parked_time: float, vehicle_type: str) -> int:
        """
        Tính phí theo giờ (đơn giản).
        Bạn có thể thay đổi rule theo yêu cầu.
        """
        vehicle_type = vehicle_type.strip().lower()
        hours_parked = int(parked_time // 3600)

        # Fee tables
        fees = {
            "car":        (20000, 40000, 60000, 120000),
            "motorbike":  (10000, 20000, 30000, 60000),
            "other":      (5000,  10000, 15000, 30000),
        }
        if vehicle_type not in fees:
            return 0

        fee_1, fee_2, fee_3, fee_extra = fees[vehicle_type]

        if hours_parked <= 3:
            return fee_1
        elif hours_parked <= 13:
            return fee_2
        elif hours_parked < 24:
            return fee_3
        else:
            return fee_extra

    # -----------------------------------------
    # NODE 5: SEARCH (plate lookup - O(1))
    # -----------------------------------------
    def find_vehicle(self, plate: str):
        plate = plate.strip().upper()
        if plate not in self.index:
            print(f"Xe {plate} không có trong hệ thống.")
            return

        rec = self.index[plate]
        print(f"Xe {plate} - trạng thái: {rec['status']}")
        if rec["status"] == "IN":
            print(f"Đang ở: {rec['spot']}")
            print(f"Thời gian vào: {time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(rec['time_in']))}")
        elif rec["status"] == "WAITING":
            print("Xe đang ở hàng đợi WAITING.")
        else:
            print("Xe đã OUT.")
            print(f"Thời gian vào: {time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(rec['time_in']))}")
            print(f"Thời gian ra : {time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(rec['time_out']))}")

    # -----------------------------------------
    # NODE 6: WAITING QUEUE ops
    # -----------------------------------------
    def _enqueue_waiting(self, vehicle_type: str, plate: str):
        # tránh duplicate waiting
        if plate in self.index and self.index[plate]["status"] == "WAITING":
            print(f"Xe {plate} đã ở WAITING.")
            return

        now = time.time()
        self.waiting_queue.append((vehicle_type, plate))
        self.index[plate] = {
            "vehicle_type": vehicle_type,
            "zone": None,
            "slot": None,
            "time_in": now,
            "time_out": None,
            "status": "WAITING",
            "spot": "WAITING_QUEUE",
        }
        print(f"Xe {plate} -> WAITING (đã đưa vào hàng đợi).")

    def remove_vehicle_from_waiting_queue(self, plate: str, silent: bool = False) -> bool:
        """
        Xóa xe khỏi hàng đợi nếu khách không muốn chờ nữa.
        Trả về True nếu xóa được, False nếu không có.
        """
        plate = plate.strip().upper()
        before = len(self.waiting_queue)
        self.waiting_queue = deque([(t, p) for (t, p) in self.waiting_queue if p != plate])
        after = len(self.waiting_queue)
        removed = after < before

        if not silent:
            if removed:
                print(f"Xe {plate} đã được xóa khỏi hàng đợi.")
            else:
                print(f"Xe {plate} không có trong hàng đợi.")
        return removed

    def show_waiting_queue(self):
        print("\n--- Hàng đợi xe (WAITING) ---")
        if not self.waiting_queue:
            print("Hàng đợi trống.")
        else:
            for i, (v_type, plate) in enumerate(self.waiting_queue, 1):
                print(f"{i}. Loại xe: {v_type}, Biển số: {plate}")
        print("-----------------------------")

    # -----------------------------------------
    # NODE 7: STATUS DISPLAY
    # -----------------------------------------
    def show_parking_status(self):
        """
        Hiển thị tình trạng theo từng zone (used/total).
        """
        print("\n--- Tình trạng bãi đỗ ---")

        def print_group(prefix, title):
            print(f"\n{title}:")
            for i in range(1, 11):
                z = f"{prefix}{i}"
                used = self.zone_count[z]
                cap = self.max_capacity_zone[z]
                print(f"  Zone {z}: {used} / {cap} đã sử dụng (còn {cap - used}).")

        print_group("C", "Tầng 1 (Ô tô)")
        print_group("M", "Tầng 2 (Xe máy)")
        print_group("B", "Tầng 3 (Xe linh tinh)")

        print(f"\nTổng xe đang IN trong bãi: {self.current_total}")

    # ============================================================
    # INTERNAL HELPERS (keep system clean, avoid mixing logic)
    # ============================================================

    def _prefix_for_type(self, vehicle_type: str):
        mapping = {"car": "C", "motorbike": "M", "other": "B"}
        return mapping.get(vehicle_type.strip().lower())

    def _has_available_zone(self, prefix: str) -> bool:
        for i in range(1, 11):
            z = f"{prefix}{i}"
            if self.zone_count[z] < self.max_capacity_zone[z]:
                return True
        return False

    def _assign_parking_slot(self, vehicle_type: str, plate: str, zone: str):
        # capacity check
        if self.zone_count[zone] >= self.max_capacity_zone[zone]:
            print(f"Zone {zone} đã đầy. Xe sẽ vào WAITING.")
            self._enqueue_waiting(vehicle_type, plate)
            return

        if not self.free_slots_pool[zone]:
            print(f"Hết slot trong {zone}. Xe sẽ vào WAITING.")
            self._enqueue_waiting(vehicle_type, plate)
            return

        slot = self.free_slots_pool[zone].pop()
        self.zone_occupied[zone].add(slot)

        now = time.time()
        self.index[plate] = {
            "vehicle_type": vehicle_type,
            "zone": zone,
            "slot": slot,
            "time_in": now,
            "time_out": None,
            "status": "IN",
            "spot": f"{zone} - Ô {slot + 1}",
        }

        self.zone_count[zone] += 1
        self.current_total += 1

        print(f"✅ Xe {plate} vào {zone} - Ô {slot + 1}.")

        # optional invariant check
        if not self._check_invariants():
            print("⚠️ Cảnh báo: invariant bị vi phạm sau CHECK-IN.")

    def _admit_waiting_fifo(self):
        """
        Admit WAITING vehicles in FIFO order when slots become available.
        Rule: pick the best recommended zone (top 1) and auto-assign.
        (đúng design: WAITING -> IN khi có slot)
        """
        while self.waiting_queue:
            v_type, plate = self.waiting_queue[0]
            prefix = self._prefix_for_type(v_type)
            if prefix is None:
                # loại xe sai - loại khỏi queue
                self.waiting_queue.popleft()
                if plate in self.index:
                    self.index[plate]["status"] = "OUT"
                continue

            rec = self.suggest_zone(v_type, top_k=1)
            if not rec:
                # chưa có slot cho loại xe này -> dừng
                break

            # có slot -> nhận xe chờ
            self.waiting_queue.popleft()
            self._assign_parking_slot(v_type, plate, rec[0])
            print(f"➡️ Xe WAITING {plate} đã được nhận vào bãi (auto-assign {rec[0]}).")

    def _check_invariants(self) -> bool:
        # (1) zone_count[z] == len(occupied[z])
        for z in self.zones:
            if self.zone_count[z] != len(self.zone_occupied[z]):
                return False

        # (2) free + occupied == capacity
        for z in self.zones:
            if len(self.free_slots_pool[z]) + len(self.zone_occupied[z]) != self.max_capacity_zone[z]:
                return False

        # (3) current_total == sum zone_count
        if self.current_total != sum(self.zone_count[z] for z in self.zones):
            return False

        # (4) record IN must have zone/slot
        for plate, rec in self.index.items():
            if rec["status"] == "IN":
                if rec["zone"] is None or rec["slot"] is None:
                    return False
            if rec["status"] == "WAITING":
                # WAITING must exist in queue (soft check)
                # (không bắt buộc O(n) scan, nhưng ta check nhẹ khi cần)
                pass

        return True

    # -----------------------------------------
    # NODE 8: TERMINAL UI (demo)
    # -----------------------------------------
    def terminal(self):
        while True:
            print("\n========== PARKING MANAGEMENT ==========")
            print("1. Check-in (Xe vào bãi)")
            print("2. Check-out (Xe ra bãi)")
            print("3. Tìm xe theo biển số")
            print("4. Hiển thị tình trạng bãi")
            print("5. Hiển thị hàng đợi WAITING")
            print("6. Hủy WAITING (xóa xe khỏi hàng đợi)")
            print("7. Thoát")
            choice = input("Chọn chức năng: ").strip()

            if choice == "1":
                vehicle_type = input("Loại xe (car/motorbike/other): ")
                plate = input("Biển số xe: ")
                self.vehicle_entry(vehicle_type, plate)

            elif choice == "2":
                plate = input("Biển số xe: ")
                self.vehicle_exit(plate)

            elif choice == "3":
                plate = input("Biển số xe: ")
                self.find_vehicle(plate)

            elif choice == "4":
                self.show_parking_status()

            elif choice == "5":
                self.show_waiting_queue()

            elif choice == "6":
                plate = input("Biển số xe cần hủy WAITING: ")
                removed = self.remove_vehicle_from_waiting_queue(plate)
                if removed and plate in self.index and self.index[plate]["status"] == "WAITING":
                    del self.index[plate]  # đồng bộ index
                    print(f"Đã xóa {plate} khỏi index (WAITING).")

            elif choice == "7":
                print("Thoát chương trình.")
                break
            else:
                print("Lựa chọn không hợp lệ.")


if __name__ == "__main__":
    parking_lot = ParkingLot()
    parking_lot.terminal()

import time
from collections import deque

class ParkingLot:
    """
    Parking Management System (DSA-oriented)
    ------------------------------------------------------------
      - Zone: C1..C10 (car), M1..M10 (motorbike), B1..B10 (other)
      - Core data structures:
          * Hash Table (dict): index: plate -> record
          * Queue (deque): waiting_queue (FIFO)
          * Array/List pool: free_slots_pool[zone] (slot ids available)
          * Occupied set: zone_occupied[zone] (slot ids in-use) -> O(1) add/remove
          * Counters: zone_count[zone], current_total
      - Invariants:
          (1) zone_count[z] == len(zone_occupied[z])
          (2) len(free_slots_pool[z]) + len(zone_occupied[z]) == max_capacity_zone[z]
          (3) current_total == sum(zone_count[z] for z in all zones)
    """

    # -----------------------------
    # NODE 0: INIT / SETUP SYSTEM
    # -----------------------------
    def __init__(self):
        # Queue: xe chờ (WAITING) - FIFO
        self.waiting_queue = deque()

        # Hash Table: plate -> record
        self.index = {}

        # Define zones
        self.zones = (
            [f"C{i}" for i in range(1, 11)] +  # cars
            [f"M{i}" for i in range(1, 11)] +  # motorbikes
            [f"B{i}" for i in range(1, 11)]    # other
        )

        # Capacity per zone (default 100 slots each)
        self.max_capacity_zone = {z: 100 for z in self.zones}

        # Occupied slots per zone (set -> O(1) add/remove)
        self.zone_occupied = {z: set() for z in self.zones}

        # Free slots pool per zone (list of slot ids 0..capacity-1)
        self.free_slots_pool = {z: list(range(self.max_capacity_zone[z])) for z in self.zones}

        # Counters
        self.zone_count = {z: 0 for z in self.zones}
        self.current_total = 0

    # ---------------------------------------------------------
    # TEST MODE SUPPORT: reduce capacity for selected zones
    # ---------------------------------------------------------
    def apply_test_capacity(self, new_capacity: int, zone_prefixes=("C", "M", "B")):
        """
        Reduce capacity of zones for testing to avoid manual 100 entries.
        This will RESET affected zones to an empty state to keep invariants valid.
        IMPORTANT: Only use in testing BEFORE real operations.
        """
        new_capacity = int(new_capacity)
        if new_capacity <= 0:
            print("Test capacity must be > 0.")
            return

        # reset all affected zones to empty (safe + invariant friendly)
        affected_zones = [z for z in self.zones if z[0] in zone_prefixes]

        # Remove any existing IN vehicles that belong to affected zones
        plates_to_delete = []
        for plate, rec in self.index.items():
            if rec.get("status") == "IN" and rec.get("zone") in affected_zones:
                plates_to_delete.append(plate)
        for plate in plates_to_delete:
            del self.index[plate]

        # Also clear WAITING queue entries of those types? (optional)
        # For simplicity, we keep WAITING queue as-is, but note: those records might still exist in index.
        # In your report/testing, apply test mode at the start so queue is empty anyway.

        # Reset zone structures
        for z in affected_zones:
            self.max_capacity_zone[z] = new_capacity
            self.zone_occupied[z].clear()
            self.free_slots_pool[z] = list(range(new_capacity))
            self.zone_count[z] = 0

        # Recompute current_total from scratch
        self.current_total = sum(self.zone_count[z] for z in self.zones)

        print(f"✅ TEST MODE: set capacity={new_capacity} for zones with prefixes {zone_prefixes}.")
        print("   (Affected zones reset to empty to keep invariants consistent.)")

    # ------------------------------------------
    # NODE 1: CHECK-IN ENTRY POINT (vehicle in)
    # ------------------------------------------
    def vehicle_entry(self, vehicle_type: str, plate: str):
        """
        CHECK-IN flow:
          1) Validate input
          2) Duplicate check in Hash Table (index)
          3) If full -> enqueue WAITING
          4) Else -> recommend zones (top K)
          5) Guard selects zone (human-in-loop)
          6) Allocate slot from free_slots_pool[zone]
          7) Update index + counters + occupied sets (maintain invariants)
        """
        vehicle_type = vehicle_type.strip().lower()
        plate = plate.strip().upper()

        if not plate:
            print("Biển số không hợp lệ.")
            return

        # (Step 2) Duplicate check: nếu xe đang IN thì reject
        if plate in self.index and self.index[plate]["status"] == "IN":
            print(f"Xe {plate} đã có trong bãi (IN).")
            return

        expected_prefix = self._prefix_for_type(vehicle_type)
        if expected_prefix is None:
            print("Loại xe không hợp lệ. Chỉ nhận: car / motorbike / other.")
            return

        # (Step 3) Nếu toàn bộ zone của loại đó đều full -> WAITING
        if not self._has_available_zone(expected_prefix):
            print("Toàn bộ bãi cho loại xe này đã đầy. Xe sẽ vào hàng đợi WAITING.")
            self._enqueue_waiting(vehicle_type, plate)
            return

        # (Step 4) Recommend zones
        recommended = self.suggest_zone(vehicle_type)
        print("\n--- CHECK-IN ---")
        print(f"Các zone gợi ý: {', '.join(recommended)}")
        zone = input("Chọn zone (vd: C1, M3, B2): ").strip().upper()

        if zone not in self.max_capacity_zone:
            print("Zone không tồn tại. Xe sẽ vào hàng đợi WAITING.")
            self._enqueue_waiting(vehicle_type, plate)
            return

        if not zone.startswith(expected_prefix):
            print("Chọn sai loại zone. Xe sẽ vào hàng đợi WAITING.")
            self._enqueue_waiting(vehicle_type, plate)
            return

        # (Step 6,7) Allocate & update
        self._assign_parking_slot(vehicle_type, plate, zone)

    # -------------------------------------------------
    # NODE 2: CHECK-OUT ENTRY POINT (vehicle out)
    # -------------------------------------------------
    def vehicle_exit(self, plate: str):

        plate = plate.strip().upper()

        if plate not in self.index:
            print("Xe không có trong hệ thống (NOT FOUND).")
            return

        record = self.index[plate]
        status = record["status"]

        print("\n--- CHECK-OUT ---")

        if status == "WAITING":
            removed = self.remove_vehicle_from_waiting_queue(plate, silent=True)
            if removed:
                del self.index[plate]
                print(f"Xe {plate} đang WAITING -> đã hủy chờ và xóa khỏi hệ thống.")
            else:
                del self.index[plate]
                print(f"Xe {plate} WAITING -> xóa khỏi index (không tìm thấy trong queue).")
            return
        if status == "OUT":
            print(f"Xe {plate} đã OUT trước đó.")
            return
        if status != "IN":
            print("Trạng thái xe không hợp lệ.")
            return

        entry_time = record["time_in"]
        exit_time = time.time()
        parked_time = exit_time - entry_time

        fee = self.calculate_fee(parked_time, record["vehicle_type"])
        total_minutes = int(parked_time // 60)
        hours = total_minutes // 60
        minutes = total_minutes % 60
        duration_str = f"{hours} giờ {minutes} phút"

        print(f"Xe {plate} ra khỏi bãi. Thời gian đỗ: {duration_str}. Phí: {fee} VND.")
        print(f"Thời gian vào: {time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(entry_time))}")
        print(f"Thời gian ra : {time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(exit_time))}")

        zone = record["zone"]
        slot = record["slot"]
        self.zone_occupied[zone].remove(slot)         # O(1)
        self.free_slots_pool[zone].append(slot)       # O(1)
        self.zone_count[zone] -= 1
        self.current_total -= 1
        record["time_out"] = exit_time
        record["status"] = "OUT"

        self._admit_waiting_fifo()

        # optional invariant check
        if not self._check_invariants():
            print("⚠️ Cảnh báo: invariant bị vi phạm (kiểm tra lại logic cập nhật dữ liệu).")

    # -------------------------------------------------
    # NODE 3: ZONE RECOMMENDATION (top K by remaining)
    # -------------------------------------------------
    def suggest_zone(self, vehicle_type: str, top_k: int = 3):
        """
        Recommend zones by remaining capacity descending.
        remaining(z) = max_capacity_zone[z] - zone_count[z]
        """
        vehicle_type = vehicle_type.strip().lower()
        prefix = self._prefix_for_type(vehicle_type)
        if prefix is None:
            return []

        candidates = [z for z in self.zones if z.startswith(prefix)]
        remaining = [(z, self.max_capacity_zone[z] - self.zone_count[z]) for z in candidates]
        remaining = [x for x in remaining if x[1] > 0]

        remaining.sort(key=lambda x: (-x[1], x[0]))  # stable tie-break
        return [z for z, _ in remaining[:top_k]]

    # -----------------------------------------
    # NODE 4: FEE SERVICE (billing)
    # -----------------------------------------
    def calculate_fee(self, parked_time: float, vehicle_type: str) -> int:
        """
        Tính phí theo giờ (đơn giản).
        """
        vehicle_type = vehicle_type.strip().lower()
        hours_parked = int(parked_time // 3600)

        fees = {
            "car":        (20000, 40000, 60000, 120000),
            "motorbike":  (10000, 20000, 30000, 60000),
            "other":      (5000,  10000, 15000, 30000),
        }
        if vehicle_type not in fees:
            return 0

        fee_1, fee_2, fee_3, fee_extra = fees[vehicle_type]

        if hours_parked <= 3:
            return fee_1
        elif hours_parked <= 13:
            return fee_2
        elif hours_parked < 24:
            return fee_3
        else:
            return fee_extra

    # -----------------------------------------
    # NODE 5: SEARCH (plate lookup - O(1))
    # -----------------------------------------
    def find_vehicle(self, plate: str):
        plate = plate.strip().upper()
        if plate not in self.index:
            print(f"Xe {plate} không có trong hệ thống.")
            return

        rec = self.index[plate]
        print(f"Xe {plate} - trạng thái: {rec['status']}")
        if rec["status"] == "IN":
            print(f"Đang ở: {rec['spot']}")
            print(f"Thời gian vào: {time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(rec['time_in']))}")
        elif rec["status"] == "WAITING":
            print("Xe đang ở hàng đợi WAITING.")
        else:
            print("Xe đã OUT.")
            print(f"Thời gian vào: {time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(rec['time_in']))}")
            print(f"Thời gian ra : {time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(rec['time_out']))}")

    # -----------------------------------------
    # NODE 6: WAITING QUEUE ops
    # -----------------------------------------
    def _enqueue_waiting(self, vehicle_type: str, plate: str):
        # tránh duplicate waiting
        if plate in self.index and self.index[plate]["status"] == "WAITING":
            print(f"Xe {plate} đã ở WAITING.")
            return

        now = time.time()
        self.waiting_queue.append((vehicle_type, plate))
        self.index[plate] = {
            "vehicle_type": vehicle_type,
            "zone": None,
            "slot": None,
            "time_in": now,
            "time_out": None,
            "status": "WAITING",
            "spot": "WAITING_QUEUE",
        }
        print(f"Xe {plate} -> WAITING (đã đưa vào hàng đợi).")

    def remove_vehicle_from_waiting_queue(self, plate: str, silent: bool = False) -> bool:
        """
        Xóa xe khỏi hàng đợi nếu khách không muốn chờ nữa.
        Trả về True nếu xóa được, False nếu không có.
        """
        plate = plate.strip().upper()
        before = len(self.waiting_queue)
        self.waiting_queue = deque([(t, p) for (t, p) in self.waiting_queue if p != plate])
        after = len(self.waiting_queue)
        removed = after < before

        if not silent:
            if removed:
                print(f"Xe {plate} đã được xóa khỏi hàng đợi.")
            else:
                print(f"Xe {plate} không có trong hàng đợi.")
        return removed

    def show_waiting_queue(self):
        print("\n--- Hàng đợi xe (WAITING) ---")
        if not self.waiting_queue:
            print("Hàng đợi trống.")
        else:
            for i, (v_type, plate) in enumerate(self.waiting_queue, 1):
                print(f"{i}. Loại xe: {v_type}, Biển số: {plate}")
        print("-----------------------------")

    # -----------------------------------------
    # NODE 7: STATUS DISPLAY
    # -----------------------------------------
    def show_parking_status(self):
        """
        Hiển thị tình trạng theo từng zone (used/total).
        """
        print("\n--- Tình trạng bãi đỗ ---")

        def print_group(prefix, title):
            print(f"\n{title}:")
            for i in range(1, 11):
                z = f"{prefix}{i}"
                used = self.zone_count[z]
                cap = self.max_capacity_zone[z]
                print(f"  Zone {z}: {used} / {cap} đã sử dụng (còn {cap - used}).")

        print_group("C", "Tầng 1 (Ô tô)")
        print_group("M", "Tầng 2 (Xe máy)")
        print_group("B", "Tầng 3 (Xe linh tinh)")

        print(f"\nTổng xe đang IN trong bãi: {self.current_total}")

    # ============================================================
    # INTERNAL HELPERS
    # ============================================================

    def _prefix_for_type(self, vehicle_type: str):
        mapping = {"car": "C", "motorbike": "M", "other": "B"}
        return mapping.get(vehicle_type.strip().lower())

    def _has_available_zone(self, prefix: str) -> bool:
        for i in range(1, 11):
            z = f"{prefix}{i}"
            if self.zone_count[z] < self.max_capacity_zone[z]:
                return True
        return False

    def _assign_parking_slot(self, vehicle_type: str, plate: str, zone: str):
        # capacity check
        if self.zone_count[zone] >= self.max_capacity_zone[zone]:
            print(f"Zone {zone} đã đầy. Xe sẽ vào WAITING.")
            self._enqueue_waiting(vehicle_type, plate)
            return

        if not self.free_slots_pool[zone]:
            print(f"Hết slot trong {zone}. Xe sẽ vào WAITING.")
            self._enqueue_waiting(vehicle_type, plate)
            return

        slot = self.free_slots_pool[zone].pop()
        self.zone_occupied[zone].add(slot)

        now = time.time()
        self.index[plate] = {
            "vehicle_type": vehicle_type,
            "zone": zone,
            "slot": slot,
            "time_in": now,
            "time_out": None,
            "status": "IN",
            "spot": f"{zone} - Ô {slot + 1}",
        }

        self.zone_count[zone] += 1
        self.current_total += 1

        print(f"✅ Xe {plate} vào {zone} - Ô {slot + 1}.")

        if not self._check_invariants():
            print("⚠️ Cảnh báo: invariant bị vi phạm sau CHECK-IN.")

    def _admit_waiting_fifo(self):
        """
        Admit WAITING vehicles in FIFO order when slots become available.
        Auto-assign to best recommended zone (top 1).
        """
        while self.waiting_queue:
            v_type, plate = self.waiting_queue[0]
            prefix = self._prefix_for_type(v_type)
            if prefix is None:
                self.waiting_queue.popleft()
                if plate in self.index:
                    self.index[plate]["status"] = "OUT"
                continue

            rec = self.suggest_zone(v_type, top_k=1)
            if not rec:
                break

            self.waiting_queue.popleft()
            self._assign_parking_slot(v_type, plate, rec[0])
            print(f"➡️ Xe WAITING {plate} đã được nhận vào bãi (auto-assign {rec[0]}).")

    def _check_invariants(self) -> bool:
        for z in self.zones:
            if self.zone_count[z] != len(self.zone_occupied[z]):
                return False

        for z in self.zones:
            if len(self.free_slots_pool[z]) + len(self.zone_occupied[z]) != self.max_capacity_zone[z]:
                return False

        if self.current_total != sum(self.zone_count[z] for z in self.zones):
            return False

        for _, rec in self.index.items():
            if rec["status"] == "IN":
                if rec["zone"] is None or rec["slot"] is None:
                    return False

        return True

    # -----------------------------------------
    # NODE 8: TERMINAL UI (demo)
    # -----------------------------------------
    def terminal(self):
        while True:
            print("\n========== PARKING MANAGEMENT ==========")
            print("1. Check-in (Xe vào bãi)")
            print("2. Check-out (Xe ra bãi)")
            print("3. Tìm xe theo biển số")
            print("4. Hiển thị tình trạng bãi")
            print("5. Hiển thị hàng đợi WAITING")
            print("6. Hủy WAITING (xóa xe khỏi hàng đợi)")
            print("7. Thoát")
            choice = input("Chọn chức năng: ").strip()

            if choice == "1":
                vehicle_type = input("Loại xe (car/motorbike/other): ")
                plate = input("Biển số xe: ")
                self.vehicle_entry(vehicle_type, plate)

            elif choice == "2":
                plate = input("Biển số xe: ")
                self.vehicle_exit(plate)

            elif choice == "3":
                plate = input("Biển số xe: ")
                self.find_vehicle(plate)

            elif choice == "4":
                self.show_parking_status()

            elif choice == "5":
                self.show_waiting_queue()

            elif choice == "6":
                plate = input("Biển số xe cần hủy WAITING: ")
                removed = self.remove_vehicle_from_waiting_queue(plate)
                if removed and plate in self.index and self.index[plate]["status"] == "WAITING":
                    del self.index[plate]
                    print(f"Đã xóa {plate} khỏi index (WAITING).")

            elif choice == "7":
                print("Thoát chương trình.")
                break
            else:
                print("Lựa chọn không hợp lệ.")


if __name__ == "__main__":
    parking_lot = ParkingLot()

    # =========================
    # TEST MODE (CÁCH 2)
    # =========================
    TEST_MODE = True
    TEST_CAPACITY_PER_ZONE = 3  # ví dụ: 3 slot/zone để test đầy bãi nhanh

    if TEST_MODE:
        # Giảm capacity cho tất cả zone (C, M, B) để test nhanh (bạn có thể chỉ giảm "C" nếu muốn)
        parking_lot.apply_test_capacity(TEST_CAPACITY_PER_ZONE, zone_prefixes=("C", "M", "B"))
        # Nếu bạn chỉ muốn test riêng ô tô:
        # parking_lot.apply_test_capacity(TEST_CAPACITY_PER_ZONE, zone_prefixes=("C",))

    parking_lot.terminal()